maanden= ['januari', 'februari', 'maart', 'april', 'mei', 'juni','july','augustus','september','oktober','november','december']
print (maanden)
print (maanden[6])
maanden[6] = "juli"
print (maanden[6])
print(maanden[0] + "\n")
print(maanden[1] + "\n")
print(maanden[2] + "\n")
print(maanden[3] + "\n")
print(maanden[4] + "\n")
print(maanden[5] + "\n")
print(maanden[6] + "\n")
print(maanden[7] + "\n")
print(maanden[8] + "\n")
print(maanden[9] + "\n")
print(maanden[10] + "\n")
print(maanden[11])
